name: communities_addon
description: Flutter addon package for the RocketLMS Communities & Chatroom module.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
